# Generated by Django 4.1.6 on 2023-06-22 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GalleryItem",
            new_name="GuestbookItem",
        ),
    ]
